'use client'

import '../style/globals.css'

import Navigation from '@/components/navigation'
import PermanentSidebar from '@/components/permanent-side-bar'
import SideBar from '@/components/sliding-side-bar'

import { motion } from "framer-motion"
import { useState } from 'react'

export const metadata = {
  title: 'Moo Market Home',
  description: 'Generated by create next app',
}

const variants = {
  sidebarClosed: { x: 0 },
  sidebarOpen: { x: 250 }
}

export default function RootLayout({ children }) {
  const [bodyStatus, setBodyStatus] = useState(false);
  return (
    <html lang="en">
      <body>
        <PermanentSidebar />
        <Navigation >
          {
            (status) => {
              setBodyStatus(status)
              return <SideBar status={status} />
            }
          }
        </Navigation>
        <motion.div
          initial={{x:50,y:100}}
          animate={bodyStatus?'sidebarOpen':'sdiebarClosed'}
          variants={variants}
        >
          {children}
        </motion.div>
      </body>
    </html>
  )
}
